### PR TITLE
Update balances.rs

### PR DESCRIPTION
**Pull request by yhamacnu**
Call method from another method.
"good first issue"

### CODE REVIEW

**Comment by shawntabrizi** [comment]
this is not the correct syntax, and not really a change i think needs to be made

**Comment by yhamacnu** [comment]
Looked redundant to me, but it's your repo - your call.
Just for my sake: what would be the correct syntax?

**Comment by shawntabrizi** [comment]
you are referencing a function inside the impl of an object.

You need to use capital `Self::function_name`

**Comment by shawntabrizi** [comment]
my mistake, the syntax was right. I thought it might be `Self::set_balance`, but this works.

in any case, i am also not sure that this is "better". its another function call, an additional clone, etc...

if you explained more what you are looking to achieve, i could understand more your suggestion here, but this really doesn't seem like it contributes to the tutorial

**Comment by yhamacnu** [comment]
I was looking for "good first issue"s to contribute and start with a small pr change.

Had a look through the issues, but there were just a few, so I will have to pick one of them.

**Pull request closed without merging**
